<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-4BSLIP7" failures="1" tests="12" name="Learning Batch TestNGTest" time="9.629" errors="0" timestamp="2022-08-16T16:30:31 EDT">
  <testcase classname="com.testng.code.Dependencies_TestCases" name="URLopen" time="7.337"/>
  <testcase classname="com.testng.code.Dependencies_TestCases" name="GotoSignin" time="2.055"/>
  <testcase classname="com.testng.code.Dependencies_TestCases" name="LoginPage" time="0.166"/>
  <testcase classname="com.testng.code.Always_Run" name="Login" time="0.003">
    <failure type="java.lang.AssertionError" message="failing by myself to check this test case">
      <![CDATA[java.lang.AssertionError: failing by myself to check this test case
at com.testng.code.Always_Run.Login(Always_Run.java:13)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- Login -->
  <testcase classname="com.testng.code.Always_Run" name="Logout" time="0.001"/>
  <testcase classname="com.testng.code.Sequence_Annotations" name="testCase1" time="0.001"/>
  <testcase classname="com.testng.code.Priority_TestCases_Execution" name="Ballon" time="0.0"/>
  <testcase classname="com.testng.code.Priority_TestCases_Execution" name="Coding" time="0.002"/>
  <testcase classname="com.testng.code.Priority_TestCases_Execution" name="Apple" time="0.002"/>
  <testcase classname="com.testng.code.Combination_BeforeMethod_AfterMethod" name="HomePageValidationTest" time="0.002"/>
  <testcase classname="com.testng.code.Combination_BeforeMethod_AfterMethod" name="LaunchBrowser" time="0.002"/>
  <testcase classname="com.testng.code.Combination_BeforeMethod_AfterMethod" name="LoginTest" time="0.001"/>
  <testcase classname="com.testng.code.Priority_TestCases_Execution" name="Zebra" time="0.0">
    <ignored/>
  </testcase> <!-- Zebra -->
</testsuite> <!-- Learning Batch TestNGTest -->
